### ISSUE TITLE
oh no!

### ISSUE THREAD

**Issue by jsms90** [jsms90/codecov-example#7]
sort it out!

**Comment by nelsonic** [comment]
@jsms90 _descriptive_... 😜 
(_we could help if you share a bit more detail..._)

**Comment by jsms90** [comment]
@nelsonic hahahahha. Woops!
This was purely to show Rob the functionality of Gitpom - the pomodoro timer made by another group in oath week :)

**Comment by nelsonic** [comment]
@jsms90 Cool. I briefly saw it during the demo but would love to see more...
